# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('format', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('bookcode', models.CharField(blank=True, max_length=400)),
                ('no_of_pages', models.IntegerField()),
                ('publication', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('Ratings', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.IntegerField()),
                ('is_donated', models.BooleanField()),
                ('donated_by', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authors.Author')),
            ],
        ),
    ]
